name: cyber_investigator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # ── Case data files (one JSON per case) ──
    - assets/cases/case_ghosttrace.json
    - assets/cases/case_lastlogin.json
    - assets/cases/case_deaddropsignal.json
    - assets/cases/case_echoesoftomorrow.json
    - assets/cases/case_echowithoutavoice.json

  fonts:
    - family: DotMatrix
      fonts:
        - asset: assets/DOTMATRI.TTF # noinspection YAMLSchemaValidation