name: cyber_investigator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # ── Easy Cases ────────────────────────────────────────
    - assets/cases/case_passwordheist.json
    - assets/cases/case_wifithief.json
    - assets/cases/case_fakereview.json
    - assets/cases/case_ghosttrace.json

    # ── Medium Cases ──────────────────────────────────────
    - assets/cases/case_phantomtransaction.json
    - assets/cases/case_attendancehack.json
    - assets/cases/case_socialengineer.json
    - assets/cases/case_lastlogin.json

    # ── Hard Cases ────────────────────────────────────────
    - assets/cases/case_deaddrop.json
    - assets/cases/case_echoesoftomorrow.json
    - assets/cases/case_echowithoutavoice.json
    - assets/cases/case_darkproxyattack.json

    # ── Advanced Cases ────────────────────────────────────
    - assets/cases/case_vanishingvault.json
    - assets/cases/case_mirrorprotocol.json
    - assets/cases/case_zeropointentry.json
    - assets/cases/case_ghostnetwork.json

  fonts:
    - family: DotMatrix
      fonts:
        - asset: assets/DOTMATRI.TTF # noinspection YAMLSchemaValidation